// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLKtaIP83mOmDiXHjMeESbLNcg17fn2Jo',
    appId: '1:669230742560:web:7f538b95ea7db802e61045',
    messagingSenderId: '669230742560',
    projectId: 'andromeda-chat-103f4',
    authDomain: 'andromeda-chat-103f4.firebaseapp.com',
    storageBucket: 'andromeda-chat-103f4.appspot.com',
    measurementId: 'G-XK5Q52V69P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqMDU2_RmVoR4tu8n1WdMPv3TnitTeMY',
    appId: '1:669230742560:android:f129a0d41c82701ae61045',
    messagingSenderId: '669230742560',
    projectId: 'andromeda-chat-103f4',
    storageBucket: 'andromeda-chat-103f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppIxklHGWOpBhFnYXgNQr0P-yw8riCkg',
    appId: '1:669230742560:ios:86a84cd928fabab3e61045',
    messagingSenderId: '669230742560',
    projectId: 'andromeda-chat-103f4',
    storageBucket: 'andromeda-chat-103f4.appspot.com',
    iosClientId: '669230742560-1ie11hq1n0mpo4833sftdhl14bic9t3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.andromedaChat',
  );
}
